# Generated by Django 6.0 on 2025-12-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem_get_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='get_total_price',
        ),
    ]
