# Generated by Django 5.2.4 on 2025-12-24 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='voiceprofile',
            name='sample_count',
        ),
        migrations.RemoveField(
            model_name='voiceprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='airequestlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
