# Generated by Django 6.0 on 2025-12-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='get_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
    ]
